// Test renderer only: deterministic coordinates, not real WebGL.

const markers=new Set();
class Events{constructor(){this.events={};}on(n,fn){(this.events[n]??=[]).push(fn);return this;}once(n,fn){const wrap=e=>{this.off(n,wrap);fn(e);};return this.on(n,wrap);}off(n,fn){this.events[n]=(this.events[n]||[]).filter(f=>f!==fn);return this;}fire(n,e={}){for(const fn of [...(this.events[n]||[])])fn(e);return this;}}
export class Map extends Events{constructor(o){super();this.container=document.getElementById(o.container);this.container.style.background='#e7efe8';this.center={lng:134,lat:35};this.zoom=10;this.sources={};this.layers={};this.hits=[];this.moves=[];this.canvas=document.createElement('canvas');this.container.append(this.canvas);}getContainer(){return this.container;}getCanvas(){return this.canvas;}addControl(){}resize(){this.fire('resize');}stop(){}getZoom(){return this.zoom;}getCenter(){return this.center;}jumpTo(o){this.moves.push({kind:'jumpTo',...o});return this.apply(o);}easeTo(o){this.moves.push({kind:'easeTo',...o});return this.apply(o);}flyTo(o){this.moves.push({kind:'flyTo',...o});return this.apply(o);}apply(o){if(o.center)this.center={lng:o.center[0],lat:o.center[1]};if(o.zoom)this.zoom=o.zoom;this.fire('move');return this;}panBy(offset){this.center.lng+=offset[0]/800;this.center.lat-=offset[1]/800;this.fire('move');}unproject(pt){return {lng:this.center.lng+(pt.x-this.container.clientWidth/2)/800,lat:this.center.lat-(pt.y-this.container.clientHeight/2)/800};}
  project(p){const a=Array.isArray(p)?p:[p.lng,p.lat];return {x:this.container.clientWidth/2+(a[0]-this.center.lng)*800,y:this.container.clientHeight/2-(a[1]-this.center.lat)*800};}fitBounds(bounds,options){this.moves.push({kind:'fitBounds',bounds:bounds&&bounds.coords?[...bounds.coords]:null,...options});return this;}setStyle(){this.sources={};this.layers={};this.fire('style.load');setTimeout(()=>this.fire('idle'),0);}getSource(n){return this.sources[n];}addSource(n,s){this.sources[n]={...s,setData(data){this.data=data;}};}getLayer(n){return this.layers[n];}addLayer(l){this.layers[l.id]=l;}setLayoutProperty(){}setPaintProperty(){}queryRenderedFeatures(){return this.hits;}}
export class Marker extends Events{constructor(o={}){super();this.node=o.element||document.createElement('div');this.node.classList.add('maplibregl-marker');this.node.style.position='absolute';this.draggable=!!o.draggable;}setLngLat(p){this.pos=p;this.update();return this;}getLngLat(){const a=Array.isArray(this.pos)?this.pos:[this.pos.lng,this.pos.lat];return {lng:a[0],lat:a[1]};}update(){if(this.map){const p=this.map.project(this.pos);this.node.style.left=p.x+'px';this.node.style.top=p.y+'px';}}addTo(m){this.map=m;m.container.append(this.node);m.on('move',()=>this.update());this.update();markers.add(this);return this;}getElement(){return this.node;}remove(){this.node.remove();markers.delete(this);}}
export class Popup extends Events{constructor(o={}){super();this.node=document.createElement('div');this.node.className='maplibregl-popup '+(o.className||'');this.node.style.cssText='position:absolute;width:280px;z-index:600;';this.content=document.createElement('div');this.content.className='maplibregl-popup-content';this.node.append(this.content);}setLngLat(p){this.pos=p;return this;}setDOMContent(n){this.content.replaceChildren(n);const close=document.createElement('button');close.className='maplibregl-popup-close-button';close.textContent='×';close.onclick=()=>this.remove();this.content.append(close);return this;}addTo(m){this.map=m;this.open=true;m.container.append(this.node);const update=()=>{const p=m.project(this.pos);this.node.style.left=Math.max(10,p.x-140)+'px';this.node.style.top=Math.max(85,p.y-this.node.offsetHeight-25)+'px';};update();m.on('move',update);return this;}getElement(){return this.node;}isOpen(){return !!this.open;}remove(){if(this.open){this.open=false;this.node.remove();this.fire('close');}return this;}}
export class LngLatBounds{constructor(){this.coords=[];}extend(c){this.coords.push(Array.isArray(c)?[...c]:[c.lng,c.lat]);return this;}}
export class NavigationControl{};export class AttributionControl{};
